Expand session detail display
w9jds/DeLorean-v88 pull request #17
Opened 2023-11-23 00:14 UTC by cjwhitsitt

- Show session duration in card header
- Conditionally show accordion based on session values other than type
- Conditionally show type string in name
- Conditionally show description or speakers section

2023-11-23 05:20 UTC, w9jds requested changes

2023-11-23 05:20 UTC, w9jds commented on src/controls/SessionSheet.tsx
> +  const shouldShowSpeakers = () => {
This should be memoized instead of a function, calling this a ton of times is unnecessary and a performance hit.

2023-11-23 05:20 UTC, w9jds commented on src/controls/SessionSheet.tsx
> +  const shouldShowDescription = () => {
This should be memoized instead of a function, calling this a ton of times is unnecessary and a performance hit.

2023-11-23 05:20 UTC, w9jds commented on src/controls/SessionSheet.tsx
> +      return `${hours} hr ${minutes % 60} mins`;
`date-fns` has a date differential system that should do this for you

2023-11-23 05:20 UTC, w9jds commented on src/controls/SessionSheet.tsx
> +  const shouldShowAccordion = () => {
This should be memoized instead of a function, calling this a ton of times is unnecessary and a performance hit.

2023-11-24 20:20 UTC, cjwhitsitt commented
Changes made to master from another branch

2023-11-24 20:20 UTC, closed without merging